pipeline {
    agent any
	environment {
	 DOCKERHUB_CREDENTIALS = credentials('iamkhaihoang-dockerhub')
	 GITHUB_REPO_NAME = "iamkhaihoang/devops16-app"
	 IMAGE_TAG = "1.2" 
	 IMAGE_NAME = "${GITHUB_REPO_NAME}:${IMAGE_TAG}"
	 JENKINS_DEPLOYED_MACHINE = "192.168.37.111"
	}
    stages {
        stage("Build Application") {
            steps {
                sh """
                    docker --version
                """
            }
        }
    }
}
